name: Test

on:
  push:
    branches: [ main ]
    paths:
      - 'web-interface/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'web-interface/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: web-interface

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: web-interface/package-lock.json
    
    - name: Install Dependencies
      run: npm ci
    
    - name: Lint
      run: npm run lint
    
    - name: Type Check
      run: npm run typecheck
    
    - name: Run Tests
      run: npm test -- --coverage
    
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        directory: ./web-interface/coverage
        flags: web-interface
        fail_ci_if_error: false
    
    - name: Build
      run: npm run build