# Phase 1: Single-Node Benchmarks (GC Classic)
phase_1:
  - id: TEST-G3-C7G-4-TRANSPORT
    description: "Transport simulation on Graviton3 c7g.4xlarge"
    application: gc-classic
    simulation_type: transport
    domain:
      type: global
      resolution: 4x5
    duration:
      days: 1
    hardware:
      instance_type: c7g.4xlarge
      processor_type: Graviton3
      architecture: arm64
      vcpus: 16
      memory_gb: 32
    metrics_focus: "Graviton3 baseline"

  - id: TEST-G3-C7G-4-FC
    description: "Full Chemistry simulation on Graviton3 c7g.4xlarge"
    application: gc-classic
    simulation_type: fullchem
    domain:
      type: global
      resolution: 4x5
    duration:
      days: 1
    hardware:
      instance_type: c7g.4xlarge
      processor_type: Graviton3
      architecture: arm64
      vcpus: 16
      memory_gb: 32
    metrics_focus: "Chemistry complexity impact"

# Phase 2: Multi-Node Benchmarks (GCHP) - Empty for test
phase_2: []

# Phase 3: Specialized Benchmarks - Empty for test
phase_3: []

# Phase 4: Real-World Scenarios - Empty for test
phase_4: []